### PR TITLE
Initial CI

### PR DESCRIPTION
**Pull request by asizikov**
In this PR I want to propose a couple steps in a direction to more or less mature CI process.
- Appveyor.yml config. But you need to create a new project on AppVeyor.com
- Added a unit test project. There is only one test there, but it's better than nothing, right? 

I also updated some packages.

Next step is to use FAKE for a build script and Paket to work with packages. You know, to be a real F# project. 

Sample build can be found [here](https://ci.appveyor.com/project/asizikov/octonotes/build/1.0.9)

### CODE REVIEW

**Comment by shiftkey** [comment]
> Appveyor.yml config. But you need to create a new project on AppVeyor.com

This has been enabled: https://ci.appveyor.com/project/shiftkey/octonotes

**Comment by shiftkey** [comment]
@asizikov i've given you commit rights to the repo - let me know if there's anything in particular you need from me!

**Comment by asizikov** [comment]
and we have a green build! Sweet.

**Comment by asizikov** [comment]
@shiftkey  Just to clarify: does commit rights mean that I can merge my own PR?

And could you make `master` protected after this PR was merged in?

**Comment by shiftkey** [comment]
> does commit rights mean that I can merge my own PR?

I believe so. Let me know if you can't.

> And could you make `master` protected after this PR was merged in?

Done.

**Comment by asizikov** [comment]
yep, I can merge. 👍

**Pull request merged**
